import { Expense } from "./types";

export const PRELOADED_EXPENSES: Expense[] = [
  { id: "1", date: "2026-01-08", category: "Packaging", description: "Perfume Boxes (150 pcs)", amount: 35000, paymentMethod: "Cash", notes: "Asif Bhai supplied" },
  { id: "2", date: "2026-01-08", category: "Packaging", description: "Perfume Bottles 50ml (60 pcs)", amount: 15000, paymentMethod: "Cash", notes: "First batch" },
  { id: "3", date: "2026-01-08", category: "Packaging", description: "Perfume Bottles 50ml (108 pcs)", amount: 24500, paymentMethod: "Cash", notes: "Second batch" },
  { id: "4", date: "2026-01-08", category: "Packaging", description: "Sample Bottles 5ml (150 pcs)", amount: 3450, paymentMethod: "Cash", notes: "Small sample bottles" },
  { id: "5", date: "2026-01-08", category: "Packaging", description: "Hand Bags 3 Colours", amount: 1800, paymentMethod: "Cash", notes: "Without print, 150 pcs" },
  { id: "6", date: "2026-01-08", category: "Packaging", description: "Print on Handbag + Extra Flyers", amount: 2000, paymentMethod: "Cash", notes: "Alim print wala" },
  { id: "7", date: "2026-01-08", category: "Packaging", description: "Extra Handbag + Print (50 pcs)", amount: 1000, paymentMethod: "Cash", notes: "Alim" },
  { id: "8", date: "2026-01-08", category: "Packaging", description: "Thank You Card + Delivery", amount: 2500, paymentMethod: "Cash", notes: "Ashir's cousin Zohib" },
  { id: "9", date: "2026-01-08", category: "Packaging", description: "Bubble Wrap / Ductape", amount: 500, paymentMethod: "Cash", notes: "50 rolls" },
  { id: "10", date: "2026-01-08", category: "Packaging", description: "Strings Tag (1000 pcs)", amount: 1600, paymentMethod: "Cash", notes: "Tag strings for bottles" },
  { id: "11", date: "2025-09-04", category: "Perfume Oils", description: "Fragrance Bank - 4 Oils (Charlie Elevation, Gucci Flora, Khumra Lattafa, Burberry Goddess)", amount: 24000, paymentMethod: "Invoice #19561", notes: "0.8kg total, Discount Rs 100, Paid in Full" },
  { id: "12", date: "2025-09-04", category: "Perfume Oils", description: "MMT - Khamrah Qahwa + Mont Blanc Legend", amount: 4510, paymentMethod: "Counter Cash", notes: "Invoice MMT-2025/17995" },
  { id: "13", date: "2026-01-08", category: "Perfume Oils", description: "Compounds / Additional Notes", amount: 1260, paymentMethod: "Cash", notes: "200ml each, 6 notes concentrate" },
  { id: "14", date: "2026-01-08", category: "Perfume Oils", description: "Ethanol Alcohol", amount: 2000, paymentMethod: "Cash", notes: "Solvent for formulation" },
  { id: "15", date: "2026-01-08", category: "Printing & DTF", description: "DTF Bottle Sticker", amount: 3500, paymentMethod: "Cash", notes: "Main bottle DTF" },
  { id: "16", date: "2026-01-08", category: "Printing & DTF", description: "DTF Card + Design", amount: 3500, paymentMethod: "Cash", notes: "Card printing with DTF" },
  { id: "17", date: "2026-01-08", category: "Printing & DTF", description: "DTF for Sample Bottle (5ml)", amount: 1000, paymentMethod: "Cash", notes: "Sample bottles DTF" },
  { id: "18", date: "2026-01-08", category: "Printing & DTF", description: "DTF Design", amount: 1200, paymentMethod: "Cash", notes: "Design work" },
  { id: "19", date: "2026-01-08", category: "Printing & DTF", description: "Advance for New DTF (5ml Sample)", amount: 3000, paymentMethod: "Cash", notes: "Advance payment" },
  { id: "20", date: "2026-01-08", category: "Printing & DTF", description: "Printed Flyers (150 pcs)", amount: 3150, paymentMethod: "Cash", notes: "Zain + Printers" },
  { id: "21", date: "2026-01-08", category: "Printing & DTF", description: "Story Card (with DTF)", amount: 3000, paymentMethod: "Cash", notes: "Fragrance narrative card" },
  { id: "22", date: "2026-01-08", category: "Equipment", description: "Sealer Machine", amount: 3900, paymentMethod: "Cash", notes: "For sealing boxes" },
  { id: "23", date: "2026-01-08", category: "Equipment", description: "Hot Gun", amount: 2500, paymentMethod: "Cash", notes: "For packaging" },
  { id: "24", date: "2026-01-08", category: "Equipment", description: "Weight Machine", amount: 2400, paymentMethod: "Cash", notes: "For precise measurement" },
  { id: "25", date: "2026-01-08", category: "Equipment", description: "Blender + 6 Glass Bottles", amount: 1900, paymentMethod: "Cash", notes: "For mixing formulations" },
  { id: "26", date: "2026-01-08", category: "Equipment", description: "Rikshow Bike Counter", amount: 1560, paymentMethod: "Cash", notes: "Display counter on bike" },
  { id: "27", date: "2026-01-08", category: "Digital & Marketing", description: "Website Hosting", amount: 15000, paymentMethod: "Online", notes: "Domain + hosting" },
  { id: "28", date: "2026-01-08", category: "Digital & Marketing", description: "Website Development", amount: 1500, paymentMethod: "Online", notes: "Design & development" },
  { id: "29", date: "2026-01-08", category: "Digital & Marketing", description: "Animation", amount: 4500, paymentMethod: "Cash", notes: "Brand motion graphics" },
  { id: "30", date: "2026-01-08", category: "Digital & Marketing", description: "TikTok Account Setup", amount: 2000, paymentMethod: "Online", notes: "Account setup" },
  { id: "31", date: "2026-01-08", category: "Transport", description: "Rikshaw Fare (Multiple trips)", amount: 1000, paymentMethod: "Cash", notes: "Local sourcing trips" },
  { id: "32", date: "2026-01-08", category: "Transport", description: "Rikshaw Fare (Additional)", amount: 1600, paymentMethod: "Cash", notes: "More local trips" },
  { id: "33", date: "2026-01-08", category: "Transport", description: "Bus Fare (Market visits)", amount: 1000, paymentMethod: "Cash", notes: "Light House / Bottle Bazaar" },
  { id: "34", date: "2026-01-08", category: "Transport", description: "Bus Fare (Additional)", amount: 400, paymentMethod: "Cash", notes: "Additional bus trips" },
  { id: "35", date: "2026-01-08", category: "Transport", description: "Delivery Charges", amount: 1500, paymentMethod: "Cash", notes: "Courier costs" },
  { id: "36", date: "2026-01-08", category: "Transport", description: "Travelling + Butler Paper + Bottle Sample", amount: 2550, paymentMethod: "Cash", notes: "Combined travel + supplies" },
  { id: "37", date: "2026-01-08", category: "Testing & Misc", description: "First Day Perfume Testing", amount: 5000, paymentMethod: "Cash", notes: "Initial formulation trials" },
  { id: "38", date: "2026-01-08", category: "Testing & Misc", description: "Bottle Testing", amount: 3500, paymentMethod: "Cash", notes: "Quality testing of bottles" },
  { id: "39", date: "2026-01-08", category: "Testing & Misc", description: "Product Sample (Initial)", amount: 250, paymentMethod: "Cash", notes: "Sample for review" },
];

export const TOTAL_INVESTMENT = 189530;
